### ISSUE TITLE
Inconsistent formatting with `import-export-comma-style: leading`

### ISSUE THREAD

**Issue by novadev94** [fourmolu/fourmolu#174]
**Is your feature request specific to Fourmolu?**
- [x] Yes, this feature is not relevant to Ormolu

**Describe the current + desired formatting**

Current

```hs
import Module
  ( TypeA
      ( ConstructorA,
      fieldA1,
      fieldA2
      )
  , TypeB
    ( ConstructorB,
    fieldB1,
    fieldB2
    )
  )
```

Desired
```hs
import Module
  ( TypeA
    ( ConstructorA
    , fieldA1
    , fieldA2
    )
  , TypeB
    ( ConstructorB
    , fieldB1
    , fieldB2
    )
  )
```

** Configuration
```yaml
indentation: 2
comma-style: leading
import-export-comma-style: leading
record-brace-space: true
indent-wheres: true
respectful: true
haddock-style: single-line
newlines-between-decls: 1
# Conflicts with import-export-comma-style if `true`
diff-friendly-import-export: false
```
