### ISSUE TITLE
Leading arrows and Unicode misalignment

### ISSUE THREAD

**Issue by shlevy** [fourmolu/fourmolu#278]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Describe the bug**

With unicode syntax, a forall dot, and leading arrows, fourmolu misaligns the line with the dot:

```haskell
  generalAllocate
    ∷ ∀ a
     . GeneralAllocate (AllocationContext (AllocateViaResource m)) SomeException () () a
    → AllocateViaResource m (ReleaseKey, a)
```

My config:

```yaml
---
indentation: 2
function-arrows: leading
comma-style: leading
import-export-style: leading
indent-wheres: false
record-brace-space: false
newlines-between-decls: 1
haddock-style: multi-line
haddock-style-module:
let-style: auto
in-style: right-align
respectful: false
fixities: []
unicode: always

```
